services:
  - type: web
    name: my-telegram-bot
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python bot_telegram/my_bot_v2.py
    plan: free
